apiVersion: apps/v1
kind: Deployment
metadata:
  name: rriv-api
spec:
  template:
    spec:
      containers:
        - name: rriv-api
          env:
            - name: KEYCLOAK_URL
              value: https://auth-dev.rriv.org
            - name: KEYCLOAK_REALM
              value: rriv-beta-dev
