apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment.yaml
images:
  - name: registry.digitalocean.com/rriv/rriv-api
    newTag: 1.0.7
