apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment.yaml
  - path: migration-job.yaml
  - target:
      kind: CronJob
      name: rriv-api-reconcile-sweep
    patch: |
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: rriv-api-reconcile-sweep
      spec:
        jobTemplate:
          spec:
            template:
              metadata:
                annotations:
                  vault.hashicorp.com/agent-inject-secret-config: "secret/data/staging-rriv-api-creds"
                  vault.hashicorp.com/agent-inject-template-config: |
                    {{ with secret "secret/data/staging-rriv-api-creds" }}
                    DATABASE_URL="{{ .Data.data.database_url }}"
                    KEYCLOAK_CLIENT_SECRET="{{ .Data.data.keycloak_client_secret }}"
                    KEYCLOAK_AUTH_CLIENT_SECRET="{{ .Data.data.keycloak_auth_client_secret }}"
                    CHIRPSTACK_API_KEY="{{ .Data.data.chirpstack_downlink_key }}"
                    DATABASE_CA_CRT="{{ .Data.data.database_ca_cert }}"
                    {{ end }}
              spec:
                containers:
                  - name: reconcile
                    env:
                      - name: KEYCLOAK_URL
                        value: https://auth.staging.rriv.org
                      - name: KEYCLOAK_REALM
                        value: rriv-beta-staging
  - target:
      kind: CronJob
      name: rriv-api-reconcile-full
    patch: |
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: rriv-api-reconcile-full
      spec:
        jobTemplate:
          spec:
            template:
              metadata:
                annotations:
                  vault.hashicorp.com/agent-inject-secret-config: "secret/data/staging-rriv-api-creds"
                  vault.hashicorp.com/agent-inject-template-config: |
                    {{ with secret "secret/data/staging-rriv-api-creds" }}
                    DATABASE_URL="{{ .Data.data.database_url }}"
                    KEYCLOAK_CLIENT_SECRET="{{ .Data.data.keycloak_client_secret }}"
                    KEYCLOAK_AUTH_CLIENT_SECRET="{{ .Data.data.keycloak_auth_client_secret }}"
                    CHIRPSTACK_API_KEY="{{ .Data.data.chirpstack_downlink_key }}"
                    DATABASE_CA_CRT="{{ .Data.data.database_ca_cert }}"
                    {{ end }}
              spec:
                containers:
                  - name: reconcile
                    env:
                      - name: KEYCLOAK_URL
                        value: https://auth.staging.rriv.org
                      - name: KEYCLOAK_REALM
                        value: rriv-beta-staging
images:
  - name: registry.digitalocean.com/rriv/rriv-api
    newTag: v1.7.7
