apiVersion: apps/v1
kind: Deployment
metadata:
  name: rriv-api
  labels:
    app: rriv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rriv-api
  template:
    metadata:
      labels:
        app: rriv-api
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'webapp'
        vault.hashicorp.com/auth-path: 'auth/kubernetes-rriv'
        vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/dev-database-creds'
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{ with secret "secret/data/dev-database-creds" }}
          export DATABASE_URL={{ .Data.data.database_url }}
          {{ end }}
    spec:
      serviceAccountName: internal-app
      imagePullSecrets:
        - name: registry-rriv
      containers:
        - name: rriv-api
          command: ["/bin/sh", "-c"]
          args:
            - |
              timeout=20
              elapsed=0
              while [ ! -f /vault/secrets/credentials ]; do
                if [ $elapsed -ge $timeout ]; then
                  echo "Timeout waiting for Vault to inject secrets"
                  exit 1
                fi
                echo "Waiting for Vault to inject secrets..."
                sleep 2
                elapsed=$((elapsed + 2))
              done
              echo "Vault secrets injected"
              . /vault/secrets/credentials
              echo "starting service"
              exec npm start
          image: rrivirr/rriv-api:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_SCHEMA
              value: rriv
