name: Semantic release

on:
  push:
    branches:
      - main

env:
  project-directory: ./

jobs:
  semantic-release:
    name: Release and Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: npm clean install
        run: npm ci
        working-directory: ${{ env.project-directory }}

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
